package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Amphitheater generated by hbm2java
 */
@Entity
@Table(name = "Amphitheater")
public class Amphitheater implements java.io.Serializable {

	private int id;
	private Serializable amphitheaterName;
	private Serializable amphitheaterAddress;
	private Set<Schedule> schedules = new HashSet<Schedule>(0);
	private Set<SchoolroomAmphi> schoolroomAmphis = new HashSet<SchoolroomAmphi>(0);

	public Amphitheater() {
	}

	public Amphitheater(int id, Serializable amphitheaterName) {
		this.id = id;
		this.amphitheaterName = amphitheaterName;
	}

	public Amphitheater(int id, Serializable amphitheaterName, Serializable amphitheaterAddress, Set<Schedule> schedules, Set<SchoolroomAmphi> schoolroomAmphis) {
		this.id = id;
		this.amphitheaterName = amphitheaterName;
		this.amphitheaterAddress = amphitheaterAddress;
		this.schedules = schedules;
		this.schoolroomAmphis = schoolroomAmphis;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Amphitheater_name", nullable = false)
	public Serializable getAmphitheaterName() {
		return this.amphitheaterName;
	}

	public void setAmphitheaterName(Serializable amphitheaterName) {
		this.amphitheaterName = amphitheaterName;
	}

	@Column(name = "Amphitheater_address")
	public Serializable getAmphitheaterAddress() {
		return this.amphitheaterAddress;
	}

	public void setAmphitheaterAddress(Serializable amphitheaterAddress) {
		this.amphitheaterAddress = amphitheaterAddress;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "amphitheater")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "amphitheater")
	public Set<SchoolroomAmphi> getSchoolroomAmphis() {
		return this.schoolroomAmphis;
	}

	public void setSchoolroomAmphis(Set<SchoolroomAmphi> schoolroomAmphis) {
		this.schoolroomAmphis = schoolroomAmphis;
	}

}
