package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Amphitheater generated by hbm2java
 */
@Entity
@Table(name = "Amphitheater")
public class Amphitheater{

	private int id;
	private String amphitheaterName;
	private String amphitheaterAddress;
	private Set<Schedule> schedules = new HashSet<Schedule>(0);
	private Set<SchoolroomAmphi> schoolroomAmphis = new HashSet<SchoolroomAmphi>(0);

	public Amphitheater() {
	}

	public Amphitheater(int id, String amphitheaterName) {
		this.id = id;
		this.amphitheaterName = amphitheaterName;
	}

	public Amphitheater(int id, String amphitheaterName, String amphitheaterAddress, Set<Schedule> schedules, Set<SchoolroomAmphi> schoolroomAmphis) {
		this.id = id;
		this.amphitheaterName = amphitheaterName;
		this.amphitheaterAddress = amphitheaterAddress;
		this.schedules = schedules;
		this.schoolroomAmphis = schoolroomAmphis;
	}

	@Id
	@Column(name = "ID")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Amphitheater_name", nullable = false)
	public String getAmphitheaterName() {
		return this.amphitheaterName;
	}

	public void setAmphitheaterName(String amphitheaterName) {
		this.amphitheaterName = amphitheaterName;
	}

	@Column(name = "Amphitheater_address")
	public String getAmphitheaterAddress() {
		return this.amphitheaterAddress;
	}

	public void setAmphitheaterAddress(String amphitheaterAddress) {
		this.amphitheaterAddress = amphitheaterAddress;
	}


	@OneToMany(mappedBy = "amphitheater")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	@OneToMany(mappedBy = "amphitheater")
	public Set<SchoolroomAmphi> getSchoolroomAmphis() {
		return this.schoolroomAmphis;
	}

	public void setSchoolroomAmphis(Set<SchoolroomAmphi> schoolroomAmphis) {
		this.schoolroomAmphis = schoolroomAmphis;
	}

}
