package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classroom generated by hbm2java
 */
@Entity
@Table(name = "Classroom")
public class Classroom{

	private String id;
	private String name;
	private String description;
	private String majorId;
	private String status;
	private Set<Schedule> schedules = new HashSet<Schedule>(0);
	private Set<ClassroomStudent> classroomStudents = new HashSet<ClassroomStudent>(0);

	public Classroom() {
	}

	public Classroom(String id) {
		this.id = id;
	}

	public Classroom(String id, String name, String description, String majorId,
			String status, Set<Schedule> schedules, Set<ClassroomStudent> classroomStudents) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.majorId = majorId;
		this.status = status;
		this.schedules = schedules;
		this.classroomStudents = classroomStudents;
	}

	@Id
	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MajorID")
	public String getMajorId() {
		return this.majorId;
	}

	public void setMajorId(String majorId) {
		this.majorId = majorId;
	}

	@Column(name = "Status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(mappedBy = "classroom")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	@OneToMany(mappedBy = "classroom")
	public Set<ClassroomStudent> getClassroomStudents() {
		return this.classroomStudents;
	}

	public void setClassroomStudents(Set<ClassroomStudent> classroomStudents) {
		this.classroomStudents = classroomStudents;
	}

}
