package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassroomStudentId generated by hbm2java
 */
@Embeddable
public class ClassroomStudentId implements java.io.Serializable {

	private byte[] classroomId;
	private Serializable studentId;

	public ClassroomStudentId() {
	}

	public ClassroomStudentId(byte[] classroomId, Serializable studentId) {
		this.classroomId = classroomId;
		this.studentId = studentId;
	}

	@Column(name = "ClassroomID", nullable = false)
	public byte[] getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(byte[] classroomId) {
		this.classroomId = classroomId;
	}

	@Column(name = "StudentID", nullable = false)
	public Serializable getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Serializable studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassroomStudentId))
			return false;
		ClassroomStudentId castOther = (ClassroomStudentId) other;

		return ((this.getClassroomId() == castOther.getClassroomId())
				|| (this.getClassroomId() != null && castOther.getClassroomId() != null
						&& Arrays.equals(this.getClassroomId(), castOther.getClassroomId())))
				&& ((this.getStudentId() == castOther.getStudentId()) || (this.getStudentId() != null
						&& castOther.getStudentId() != null && this.getStudentId().equals(castOther.getStudentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getClassroomId() == null ? 0 : Arrays.hashCode(this.getClassroomId()));
		result = 37 * result + (getStudentId() == null ? 0 : this.getStudentId().hashCode());
		return result;
	}

}
