package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "Course", schema = "dbo", catalog = "EMS_DB")
public class Course implements java.io.Serializable {

	private Serializable id;
	private Semester semester;
	private Teacher teacher;
	private Serializable name;
	private Serializable desc;
	private Serializable section;
	private Serializable status;
	private Serializable classroomId;
	private Set<Attandence> attandences = new HashSet<Attandence>(0);
	private Set<Exam> exams = new HashSet<Exam>(0);
	private Set<ClassroomStudent> classroomStudents = new HashSet<ClassroomStudent>(0);

	public Course() {
	}

	public Course(Serializable id, Serializable name) {
		this.id = id;
		this.name = name;
	}

	public Course(Serializable id, Semester semester, Teacher teacher, Serializable name, Serializable desc,
			Serializable section, Serializable status, Serializable classroomId, Set<Attandence> attandences,
			Set<Exam> exams, Set<ClassroomStudent> classroomStudents) {
		this.id = id;
		this.semester = semester;
		this.teacher = teacher;
		this.name = name;
		this.desc = desc;
		this.section = section;
		this.status = status;
		this.classroomId = classroomId;
		this.attandences = attandences;
		this.exams = exams;
		this.classroomStudents = classroomStudents;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SemeterID")
	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TeacherID")
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "Desc")
	public Serializable getDesc() {
		return this.desc;
	}

	public void setDesc(Serializable desc) {
		this.desc = desc;
	}

	@Column(name = "Section")
	public Serializable getSection() {
		return this.section;
	}

	public void setSection(Serializable section) {
		this.section = section;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "ClassroomID")
	public Serializable getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(Serializable classroomId) {
		this.classroomId = classroomId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Attandence> getAttandences() {
		return this.attandences;
	}

	public void setAttandences(Set<Attandence> attandences) {
		this.attandences = attandences;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Exam> getExams() {
		return this.exams;
	}

	public void setExams(Set<Exam> exams) {
		this.exams = exams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<ClassroomStudent> getClassroomStudents() {
		return this.classroomStudents;
	}

	public void setClassroomStudents(Set<ClassroomStudent> classroomStudents) {
		this.classroomStudents = classroomStudents;
	}

}
