package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Depart generated by hbm2java
 */
@Entity
@Table(name = "Depart")
public class Depart{

	private String id;
	private String name;
	private String desc;
	private Set<Staff> staffs = new HashSet<Staff>(0);
	private Set<Teacher> teachers = new HashSet<Teacher>(0);

	public Depart() {
	}

	public Depart(String id) {
		this.id = id;
	}

	public Depart(String id, String name, String desc, Set<Staff> staffs, Set<Teacher> teachers) {
		this.id = id;
		this.name = name;
		this.desc = desc;
		this.staffs = staffs;
		this.teachers = teachers;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "desc")
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depart")
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depart")
	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

}
