package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "Device")
public class Device {

	private int id;
	private String deviceName;
	private int amount;
	private String status;
	private Float price;
	private Set<SchoolroomDevice> schoolroomdevice = new HashSet<SchoolroomDevice>(0);

	public Device() {
	}

	public Device(int id, String deviceName, int amount) {
		this.id = id;
		this.deviceName = deviceName;
		this.amount = amount;
	}

	public Device(int id, String deviceName, int amount, String status, Float price,
			Set<SchoolroomDevice> schoolroomdevice) {
		this.id = id;
		this.deviceName = deviceName;
		this.amount = amount;
		this.status = status;
		this.price = price;
		this.schoolroomdevice = schoolroomdevice;
	}

	@Id
	@Column(name = "ID")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Device_name", nullable = false)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "Amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "Status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "price", scale = 4)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@OneToMany(mappedBy = "device")
	public Set<SchoolroomDevice> getschoolroomdevice() {
		return this.schoolroomdevice;
	}

	public void setschoolroomdevice(Set<SchoolroomDevice> schoolroomdevice) {
		this.schoolroomdevice = schoolroomdevice;
	}

}
