package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "Device", schema = "dbo", catalog = "EMS_DB")
public class Device implements java.io.Serializable {

	private int id;
	private Serializable deviceName;
	private int amount;
	private Serializable status;
	private BigDecimal price;
	private Set<SchoolroomDevice> schoolroomDevices = new HashSet<SchoolroomDevice>(0);

	public Device() {
	}

	public Device(int id, Serializable deviceName, int amount) {
		this.id = id;
		this.deviceName = deviceName;
		this.amount = amount;
	}

	public Device(int id, Serializable deviceName, int amount, Serializable status, BigDecimal price,
			Set<SchoolroomDevice> schoolroomDevices) {
		this.id = id;
		this.deviceName = deviceName;
		this.amount = amount;
		this.status = status;
		this.price = price;
		this.schoolroomDevices = schoolroomDevices;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Device_name", nullable = false)
	public Serializable getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(Serializable deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "Amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "device")
	public Set<SchoolroomDevice> getSchoolroomDevices() {
		return this.schoolroomDevices;
	}

	public void setSchoolroomDevices(Set<SchoolroomDevice> schoolroomDevices) {
		this.schoolroomDevices = schoolroomDevices;
	}

}
