package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExamResult generated by hbm2java
 */
@Entity
@Table(name = "ExamResult", schema = "dbo", catalog = "EMS_DB")
public class ExamResult implements java.io.Serializable {

	private ExamResultId id;
	private Exam exam;
	private Student student;

	public ExamResult() {
	}

	public ExamResult(ExamResultId id) {
		this.id = id;
	}

	public ExamResult(ExamResultId id, Exam exam, Student student) {
		this.id = id;
		this.exam = exam;
		this.student = student;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "examId", column = @Column(name = "ExamID")),
			@AttributeOverride(name = "studentId", column = @Column(name = "StudentID")),
			@AttributeOverride(name = "mark", column = @Column(name = "Mark", precision = 53, scale = 0)) })
	public ExamResultId getId() {
		return this.id;
	}

	public void setId(ExamResultId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ExamID", insertable = false, updatable = false)
	public Exam getExam() {
		return this.exam;
	}

	public void setExam(Exam exam) {
		this.exam = exam;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StudentID", insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
