package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExamResultId generated by hbm2java
 */
@Embeddable
public class ExamResultId implements java.io.Serializable {

	private byte[] examId;
	private Serializable studentId;
	private Double mark;

	public ExamResultId() {
	}

	public ExamResultId(byte[] examId, Serializable studentId, Double mark) {
		this.examId = examId;
		this.studentId = studentId;
		this.mark = mark;
	}

	@Column(name = "ExamID")
	public byte[] getExamId() {
		return this.examId;
	}

	public void setExamId(byte[] examId) {
		this.examId = examId;
	}

	@Column(name = "StudentID")
	public Serializable getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Serializable studentId) {
		this.studentId = studentId;
	}

	@Column(name = "Mark", precision = 53, scale = 0)
	public Double getMark() {
		return this.mark;
	}

	public void setMark(Double mark) {
		this.mark = mark;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExamResultId))
			return false;
		ExamResultId castOther = (ExamResultId) other;

		return ((this.getExamId() == castOther.getExamId()) || (this.getExamId() != null
				&& castOther.getExamId() != null && Arrays.equals(this.getExamId(), castOther.getExamId())))
				&& ((this.getStudentId() == castOther.getStudentId()) || (this.getStudentId() != null
						&& castOther.getStudentId() != null && this.getStudentId().equals(castOther.getStudentId())))
				&& ((this.getMark() == castOther.getMark()) || (this.getMark() != null && castOther.getMark() != null
						&& this.getMark().equals(castOther.getMark())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getExamId() == null ? 0 : Arrays.hashCode(this.getExamId()));
		result = 37 * result + (getStudentId() == null ? 0 : this.getStudentId().hashCode());
		result = 37 * result + (getMark() == null ? 0 : this.getMark().hashCode());
		return result;
	}

}
