package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExamType generated by hbm2java
 */
@Entity
@Table(name = "ExamType", schema = "dbo", catalog = "EMS_DB")
public class ExamType implements java.io.Serializable {

	private Serializable id;
	private Serializable name;
	private Serializable desc;
	private Set<Exam> exams = new HashSet<Exam>(0);

	public ExamType() {
	}

	public ExamType(Serializable id) {
		this.id = id;
	}

	public ExamType(Serializable id, Serializable name, Serializable desc, Set<Exam> exams) {
		this.id = id;
		this.name = name;
		this.desc = desc;
		this.exams = exams;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@Column(name = "Name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "desc")
	public Serializable getDesc() {
		return this.desc;
	}

	public void setDesc(Serializable desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "examType")
	public Set<Exam> getExams() {
		return this.exams;
	}

	public void setExams(Set<Exam> exams) {
		this.exams = exams;
	}

}
