package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MajorsSemester generated by hbm2java
 */
@Entity
@Table(name = "Majors_Semester", schema = "dbo", catalog = "EMS_DB")
public class MajorsSemester implements java.io.Serializable {

	private MajorsSemesterId id;
	private Majors majors;
	private Semester semester;
	private Subject subject;

	public MajorsSemester() {
	}

	public MajorsSemester(MajorsSemesterId id) {
		this.id = id;
	}

	public MajorsSemester(MajorsSemesterId id, Majors majors, Semester semester, Subject subject) {
		this.id = id;
		this.majors = majors;
		this.semester = semester;
		this.subject = subject;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "semesterId", column = @Column(name = "semesterID")),
			@AttributeOverride(name = "majorsId", column = @Column(name = "majorsID")),
			@AttributeOverride(name = "subjectId", column = @Column(name = "subjectID")) })
	public MajorsSemesterId getId() {
		return this.id;
	}

	public void setId(MajorsSemesterId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "majorsID", insertable = false, updatable = false)
	public Majors getMajors() {
		return this.majors;
	}

	public void setMajors(Majors majors) {
		this.majors = majors;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "semesterID", insertable = false, updatable = false)
	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subjectID", insertable = false, updatable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

}
