package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MajorsSemesterId generated by hbm2java
 */
@Embeddable
public class MajorsSemesterId implements java.io.Serializable {

	private Serializable semesterId;
	private byte[] majorsId;
	private Serializable subjectId;

	public MajorsSemesterId() {
	}

	public MajorsSemesterId(Serializable semesterId, byte[] majorsId, Serializable subjectId) {
		this.semesterId = semesterId;
		this.majorsId = majorsId;
		this.subjectId = subjectId;
	}

	@Column(name = "semesterID")
	public Serializable getSemesterId() {
		return this.semesterId;
	}

	public void setSemesterId(Serializable semesterId) {
		this.semesterId = semesterId;
	}

	@Column(name = "majorsID")
	public byte[] getMajorsId() {
		return this.majorsId;
	}

	public void setMajorsId(byte[] majorsId) {
		this.majorsId = majorsId;
	}

	@Column(name = "subjectID")
	public Serializable getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Serializable subjectId) {
		this.subjectId = subjectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MajorsSemesterId))
			return false;
		MajorsSemesterId castOther = (MajorsSemesterId) other;

		return ((this.getSemesterId() == castOther.getSemesterId()) || (this.getSemesterId() != null
				&& castOther.getSemesterId() != null && this.getSemesterId().equals(castOther.getSemesterId())))
				&& ((this.getMajorsId() == castOther.getMajorsId())
						|| (this.getMajorsId() != null && castOther.getMajorsId() != null
								&& Arrays.equals(this.getMajorsId(), castOther.getMajorsId())))
				&& ((this.getSubjectId() == castOther.getSubjectId()) || (this.getSubjectId() != null
						&& castOther.getSubjectId() != null && this.getSubjectId().equals(castOther.getSubjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSemesterId() == null ? 0 : this.getSemesterId().hashCode());
		result = 37 * result + (getMajorsId() == null ? 0 : Arrays.hashCode(this.getMajorsId()));
		result = 37 * result + (getSubjectId() == null ? 0 : this.getSubjectId().hashCode());
		return result;
	}

}
