package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MajorsSemester generated by hbm2java
 */
@Entity
@Table(name = "Majorssemester")
public class MajorsSemester{

	private int id;
	private Majors majors;
	private Semester semester;
	private Subject subject;

	public MajorsSemester() {
	}

	public MajorsSemester(int id, Majors majors, Semester semester, Subject subject) {
		this.id = id;
		this.majors = majors;
		this.semester = semester;
		this.subject = subject;
	}
	
	
	@Id
	@Column(name = "ID")
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,optional = false)
	@JoinColumn(name = "majorsID")
	public Majors getMajors() {
		return this.majors;
	}

	public void setMajors(Majors majors) {
		this.majors = majors;
	}

	@ManyToOne(fetch = FetchType.LAZY,optional = false)
	@JoinColumn(name = "semesterID")
	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	@ManyToOne(fetch = FetchType.LAZY,optional = false)
	@JoinColumn(name = "subjectID")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

}
