package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "Schedule", schema = "dbo", catalog = "EMS_DB")
public class Schedule implements java.io.Serializable {

	private Serializable id;
	private Amphitheater amphitheater;
	private Classroom classroom;
	private SchoolRoom schoolRoom;
	private StudyShift studyShift;
	private Date date;

	public Schedule() {
	}

	public Schedule(Serializable id) {
		this.id = id;
	}

	public Schedule(Serializable id, Amphitheater amphitheater, Classroom classroom, SchoolRoom schoolRoom,
			StudyShift studyShift, Date date) {
		this.id = id;
		this.amphitheater = amphitheater;
		this.classroom = classroom;
		this.schoolRoom = schoolRoom;
		this.studyShift = studyShift;
		this.date = date;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AmphitheaterID")
	public Amphitheater getAmphitheater() {
		return this.amphitheater;
	}

	public void setAmphitheater(Amphitheater amphitheater) {
		this.amphitheater = amphitheater;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ClassroomID")
	public Classroom getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoomID")
	public SchoolRoom getSchoolRoom() {
		return this.schoolRoom;
	}

	public void setSchoolRoom(SchoolRoom schoolRoom) {
		this.schoolRoom = schoolRoom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StudyShiftID")
	public StudyShift getStudyShift() {
		return this.studyShift;
	}

	public void setStudyShift(StudyShift studyShift) {
		this.studyShift = studyShift;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
