package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SchoolroomAmphiId generated by hbm2java
 */
@Embeddable
public class SchoolroomAmphiId implements java.io.Serializable {

	private Integer amphiId;
	private String schoolroomId;

	public SchoolroomAmphiId() {
	}

	public SchoolroomAmphiId(Integer amphiId, String schoolroomId) {
		this.amphiId = amphiId;
		this.schoolroomId = schoolroomId;
	}

	@Column(name = "AmphiID")
	public Integer getAmphiId() {
		return this.amphiId;
	}

	public void setAmphiId(Integer amphiId) {
		this.amphiId = amphiId;
	}

	@Column(name = "SchoolroomID")
	public String getSchoolroomId() {
		return this.schoolroomId;
	}

	public void setSchoolroomId(String schoolroomId) {
		this.schoolroomId = schoolroomId;
	}

//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof SchoolroomAmphiId))
//			return false;
//		SchoolroomAmphiId castOther = (SchoolroomAmphiId) other;
//
//		return ((this.getAmphiId() == castOther.getAmphiId()) || (this.getAmphiId() != null
//				&& castOther.getAmphiId() != null && this.getAmphiId().equals(castOther.getAmphiId())))
//				&& ((this.getSchoolroomId() == castOther.getSchoolroomId())
//						|| (this.getSchoolroomId() != null && castOther.getSchoolroomId() != null
//								&& Arrays.equals(this.getSchoolroomId(), castOther.getSchoolroomId())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (getAmphiId() == null ? 0 : this.getAmphiId().hashCode());
//		result = 37 * result + (getSchoolroomId() == null ? 0 : Arrays.hashCode(this.getSchoolroomId()));
//		return result;
//	}

}
