package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SchoolRoom generated by hbm2java
 */
@Entity
@Table(name = "Schoolroom")
public class SchoolRoom {

	private String id;
	private String name;
	private String schoolroomNumber;
	private Double surfaceArea;
	private Set<Schedule> schedule = new HashSet<Schedule>(0);
	private Set<SchoolroomAmphi> schoolroomamphi = new HashSet<SchoolroomAmphi>(0);
	private Set<SchoolroomDevice> schoolroomdevice = new HashSet<SchoolroomDevice>(0);

	public SchoolRoom() {
	}


	public SchoolRoom(String id, String name, String schoolroomNumber, Double surfaceArea,
			Set<Schedule> schedule, Set<SchoolroomAmphi> schoolroomamphi, Set<SchoolroomDevice> schoolroomdevice) {
		this.id = id;
		this.name = name;
		this.schoolroomNumber = schoolroomNumber;
		this.surfaceArea = surfaceArea;
		this.schedule = schedule;
		this.schoolroomamphi = schoolroomamphi;
		this.schoolroomdevice = schoolroomdevice;
	}

	@Id
	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SchoolroomNumber")
	public String getSchoolroomNumber() {
		return this.schoolroomNumber;
	}

	public void setSchoolroomNumber(String schoolroomNumber) {
		this.schoolroomNumber = schoolroomNumber;
	}

	@Column(name = "SurfaceArea", precision = 53, scale = 0)
	public Double getSurfaceArea() {
		return this.surfaceArea;
	}

	public void setSurfaceArea(Double surfaceArea) {
		this.surfaceArea = surfaceArea;
	}

	@OneToMany(mappedBy = "schoolroom")
	public Set<Schedule> getschedule() {
		return this.schedule;
	}

	public void setschedule(Set<Schedule> schedule) {
		this.schedule = schedule;
	}

	@OneToMany(mappedBy = "schoolroom")
	public Set<SchoolroomAmphi> getschoolroomamphi() {
		return this.schoolroomamphi;
	}

	public void setschoolroomamphi(Set<SchoolroomAmphi> schoolroomamphi) {
		this.schoolroomamphi = schoolroomamphi;
	}

	@OneToMany(mappedBy = "schoolroom")
	public Set<SchoolroomDevice> getschoolroomdevice() {
		return this.schoolroomdevice;
	}

	public void setschoolroomdevice(Set<SchoolroomDevice> schoolroomdevice) {
		this.schoolroomdevice = schoolroomdevice;
	}

}
