package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolroomAmphi generated by hbm2java
 */
@Entity
@Table(name = "Schoolroom_Amphi", schema = "dbo", catalog = "EMS_DB")
public class SchoolroomAmphi implements java.io.Serializable {

	private SchoolroomAmphiId id;
	private Amphitheater amphitheater;
	private SchoolRoom schoolRoom;

	public SchoolroomAmphi() {
	}

	public SchoolroomAmphi(SchoolroomAmphiId id) {
		this.id = id;
	}

	public SchoolroomAmphi(SchoolroomAmphiId id, Amphitheater amphitheater, SchoolRoom schoolRoom) {
		this.id = id;
		this.amphitheater = amphitheater;
		this.schoolRoom = schoolRoom;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "amphiId", column = @Column(name = "AmphiID")),
			@AttributeOverride(name = "schoolroomId", column = @Column(name = "SchoolroomID")) })
	public SchoolroomAmphiId getId() {
		return this.id;
	}

	public void setId(SchoolroomAmphiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AmphiID", insertable = false, updatable = false)
	public Amphitheater getAmphitheater() {
		return this.amphitheater;
	}

	public void setAmphitheater(Amphitheater amphitheater) {
		this.amphitheater = amphitheater;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SchoolroomID", insertable = false, updatable = false)
	public SchoolRoom getSchoolRoom() {
		return this.schoolRoom;
	}

	public void setSchoolRoom(SchoolRoom schoolRoom) {
		this.schoolRoom = schoolRoom;
	}

}
