package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolroomDevice generated by hbm2java
 */
@Entity
@Table(name = "Schoolroom_Device", schema = "dbo", catalog = "EMS_DB")
public class SchoolroomDevice implements java.io.Serializable {

	private SchoolroomDeviceId id;
	private Device device;
	private SchoolRoom schoolRoom;

	public SchoolroomDevice() {
	}

	public SchoolroomDevice(SchoolroomDeviceId id) {
		this.id = id;
	}

	public SchoolroomDevice(SchoolroomDeviceId id, Device device, SchoolRoom schoolRoom) {
		this.id = id;
		this.device = device;
		this.schoolRoom = schoolRoom;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "schoolroomId", column = @Column(name = "SchoolroomID")),
			@AttributeOverride(name = "device", column = @Column(name = "Device")) })
	public SchoolroomDeviceId getId() {
		return this.id;
	}

	public void setId(SchoolroomDeviceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Device", insertable = false, updatable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SchoolroomID", insertable = false, updatable = false)
	public SchoolRoom getSchoolRoom() {
		return this.schoolRoom;
	}

	public void setSchoolRoom(SchoolRoom schoolRoom) {
		this.schoolRoom = schoolRoom;
	}

}
