package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SchoolRoom generated by hbm2java
 */
@Entity
@Table(name = "SchoolRoom", schema = "dbo", catalog = "EMS_DB")
public class SchoolRoom implements java.io.Serializable {

	private Serializable id;
	private Serializable name;
	private Serializable schoolroomNumber;
	private Double surfaceArea;
	private Set<Schedule> schedules = new HashSet<Schedule>(0);
	private Set<SchoolroomAmphi> schoolroomAmphis = new HashSet<SchoolroomAmphi>(0);
	private Set<SchoolroomDevice> schoolroomDevices = new HashSet<SchoolroomDevice>(0);

	public SchoolRoom() {
	}

	public SchoolRoom(Serializable id) {
		this.id = id;
	}

	public SchoolRoom(Serializable id, Serializable name, Serializable schoolroomNumber, Double surfaceArea,
			Set<Schedule> schedules, Set<SchoolroomAmphi> schoolroomAmphis, Set<SchoolroomDevice> schoolroomDevices) {
		this.id = id;
		this.name = name;
		this.schoolroomNumber = schoolroomNumber;
		this.surfaceArea = surfaceArea;
		this.schedules = schedules;
		this.schoolroomAmphis = schoolroomAmphis;
		this.schoolroomDevices = schoolroomDevices;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@Column(name = "Name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "SchoolroomNumber")
	public Serializable getSchoolroomNumber() {
		return this.schoolroomNumber;
	}

	public void setSchoolroomNumber(Serializable schoolroomNumber) {
		this.schoolroomNumber = schoolroomNumber;
	}

	@Column(name = "SurfaceArea", precision = 53, scale = 0)
	public Double getSurfaceArea() {
		return this.surfaceArea;
	}

	public void setSurfaceArea(Double surfaceArea) {
		this.surfaceArea = surfaceArea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schoolRoom")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schoolRoom")
	public Set<SchoolroomAmphi> getSchoolroomAmphis() {
		return this.schoolroomAmphis;
	}

	public void setSchoolroomAmphis(Set<SchoolroomAmphi> schoolroomAmphis) {
		this.schoolroomAmphis = schoolroomAmphis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schoolRoom")
	public Set<SchoolroomDevice> getSchoolroomDevices() {
		return this.schoolroomDevices;
	}

	public void setSchoolroomDevices(Set<SchoolroomDevice> schoolroomDevices) {
		this.schoolroomDevices = schoolroomDevices;
	}

}
