package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SchoolroomDeviceId generated by hbm2java
 */
@Embeddable
public class SchoolroomDeviceId implements java.io.Serializable {

	private byte[] schoolroomId;
	private Integer device;

	public SchoolroomDeviceId() {
	}

	public SchoolroomDeviceId(byte[] schoolroomId, Integer device) {
		this.schoolroomId = schoolroomId;
		this.device = device;
	}

	@Column(name = "SchoolroomID")
	public byte[] getSchoolroomId() {
		return this.schoolroomId;
	}

	public void setSchoolroomId(byte[] schoolroomId) {
		this.schoolroomId = schoolroomId;
	}

	@Column(name = "Device")
	public Integer getDevice() {
		return this.device;
	}

	public void setDevice(Integer device) {
		this.device = device;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchoolroomDeviceId))
			return false;
		SchoolroomDeviceId castOther = (SchoolroomDeviceId) other;

		return ((this.getSchoolroomId() == castOther.getSchoolroomId())
				|| (this.getSchoolroomId() != null && castOther.getSchoolroomId() != null
						&& Arrays.equals(this.getSchoolroomId(), castOther.getSchoolroomId())))
				&& ((this.getDevice() == castOther.getDevice()) || (this.getDevice() != null
						&& castOther.getDevice() != null && this.getDevice().equals(castOther.getDevice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSchoolroomId() == null ? 0 : Arrays.hashCode(this.getSchoolroomId()));
		result = 37 * result + (getDevice() == null ? 0 : this.getDevice().hashCode());
		return result;
	}

}
