package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudyShift generated by hbm2java
 */
@Entity
@Table(name = "Study_shift")
public class StudyShift {

	private int id;
	private String nameShift;
	private String startingTime;
	private String endTime;
	private Set<Schedule> schedules = new HashSet<Schedule>(0);

	public StudyShift() {
	}

	public StudyShift(int id, String nameShift, String startingTime, String endTime) {
		this.id = id;
		this.nameShift = nameShift;
		this.startingTime = startingTime;
		this.endTime = endTime;
	}

	public StudyShift(int id, String nameShift, String startingTime, String endTime, Set<Schedule> schedules) {
		this.id = id;
		this.nameShift = nameShift;
		this.startingTime = startingTime;
		this.endTime = endTime;
		this.schedules = schedules;
	}

	@Id

	@Column(name = "ID")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name_shift", nullable = false)
	public String getNameShift() {
		return this.nameShift;
	}

	public void setNameShift(String nameShift) {
		this.nameShift = nameShift;
	}

	@Column(name = "Starting_time", nullable = false, length = 16)
	public String getStartingTime() {
		return this.startingTime;
	}

	public void setStartingTime(String startingTime) {
		this.startingTime = startingTime;
	}

	@Column(name = "End_time", nullable = false, length = 16)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@OneToMany(mappedBy = "studyShift")
	public Set<Schedule> getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set<Schedule> schedules) {
		this.schedules = schedules;
	}

}
