package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "Student", schema = "dbo", catalog = "EMS_DB")
public class Student implements java.io.Serializable {

	private Serializable id;
	private Parent parent;
	private Serializable fname;
	private Serializable lname;
	private Serializable image;
	private String email;
	private Date dob;
	private String phone;
	private Serializable address;
	private Serializable status;
	private Integer idcard;
	private Serializable classroomId;
	private Set<ClassroomStudent> classroomStudents = new HashSet<ClassroomStudent>(0);
	private Set<ExamResult> examResults = new HashSet<ExamResult>(0);
	private Set<Attandence> attandences = new HashSet<Attandence>(0);

	public Student() {
	}

	public Student(Serializable id, Serializable fname, Serializable lname, Date dob) {
		this.id = id;
		this.fname = fname;
		this.lname = lname;
		this.dob = dob;
	}

	public Student(Serializable id, Parent parent, Serializable fname, Serializable lname, Serializable image,
			String email, Date dob, String phone, Serializable address, Serializable status, Integer idcard,
			Serializable classroomId, Set<ClassroomStudent> classroomStudents, Set<ExamResult> examResults,
			Set<Attandence> attandences) {
		this.id = id;
		this.parent = parent;
		this.fname = fname;
		this.lname = lname;
		this.image = image;
		this.email = email;
		this.dob = dob;
		this.phone = phone;
		this.address = address;
		this.status = status;
		this.idcard = idcard;
		this.classroomId = classroomId;
		this.classroomStudents = classroomStudents;
		this.examResults = examResults;
		this.attandences = attandences;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ParentID")
	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	@Column(name = "Fname", nullable = false)
	public Serializable getFname() {
		return this.fname;
	}

	public void setFname(Serializable fname) {
		this.fname = fname;
	}

	@Column(name = "Lname", nullable = false)
	public Serializable getLname() {
		return this.lname;
	}

	public void setLname(Serializable lname) {
		this.lname = lname;
	}

	@Column(name = "Image")
	public Serializable getImage() {
		return this.image;
	}

	public void setImage(Serializable image) {
		this.image = image;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "Idcard")
	public Integer getIdcard() {
		return this.idcard;
	}

	public void setIdcard(Integer idcard) {
		this.idcard = idcard;
	}

	@Column(name = "ClassroomID")
	public Serializable getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(Serializable classroomId) {
		this.classroomId = classroomId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<ClassroomStudent> getClassroomStudents() {
		return this.classroomStudents;
	}

	public void setClassroomStudents(Set<ClassroomStudent> classroomStudents) {
		this.classroomStudents = classroomStudents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<ExamResult> getExamResults() {
		return this.examResults;
	}

	public void setExamResults(Set<ExamResult> examResults) {
		this.examResults = examResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Attandence> getAttandences() {
		return this.attandences;
	}

	public void setAttandences(Set<Attandence> attandences) {
		this.attandences = attandences;
	}

}
