package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "Subject", schema = "dbo", catalog = "EMS_DB")
public class Subject implements java.io.Serializable {

	private Serializable id;
	private Majors majors;
	private Serializable subjectName;
	private Serializable description;
	private Serializable status;
	private Set<MajorsSemester> majorsSemesters = new HashSet<MajorsSemester>(0);

	public Subject() {
	}

	public Subject(Serializable id) {
		this.id = id;
	}

	public Subject(Serializable id, Majors majors, Serializable subjectName, Serializable description,
			Serializable status, Set<MajorsSemester> majorsSemesters) {
		this.id = id;
		this.majors = majors;
		this.subjectName = subjectName;
		this.description = description;
		this.status = status;
		this.majorsSemesters = majorsSemesters;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MajorID")
	public Majors getMajors() {
		return this.majors;
	}

	public void setMajors(Majors majors) {
		this.majors = majors;
	}

	@Column(name = "SubjectName")
	public Serializable getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(Serializable subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<MajorsSemester> getMajorsSemesters() {
		return this.majorsSemesters;
	}

	public void setMajorsSemesters(Set<MajorsSemester> majorsSemesters) {
		this.majorsSemesters = majorsSemesters;
	}

}
