package com.example.demo.entities;
// Generated Oct 24, 2020, 7:32:02 PM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "Teacher", schema = "dbo", catalog = "EMS_DB")
public class Teacher implements java.io.Serializable {

	private Serializable id;
	private Depart depart;
	private Role role;
	private Serializable fname;
	private Serializable lname;
	private Serializable image;
	private String email;
	private Date dob;
	private String phone;
	private Serializable address;
	private Serializable status;
	private Integer level;
	private Double salary;
	private Set<Course> courses = new HashSet<Course>(0);

	public Teacher() {
	}

	public Teacher(Serializable id, Serializable fname, Serializable lname, Date dob) {
		this.id = id;
		this.fname = fname;
		this.lname = lname;
		this.dob = dob;
	}

	public Teacher(Serializable id, Depart depart, Role role, Serializable fname, Serializable lname,
			Serializable image, String email, Date dob, String phone, Serializable address, Serializable status,
			Integer level, Double salary, Set<Course> courses) {
		this.id = id;
		this.depart = depart;
		this.role = role;
		this.fname = fname;
		this.lname = lname;
		this.image = image;
		this.email = email;
		this.dob = dob;
		this.phone = phone;
		this.address = address;
		this.status = status;
		this.level = level;
		this.salary = salary;
		this.courses = courses;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DepartID")
	public Depart getDepart() {
		return this.depart;
	}

	public void setDepart(Depart depart) {
		this.depart = depart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RoleID")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "Fname", nullable = false)
	public Serializable getFname() {
		return this.fname;
	}

	public void setFname(Serializable fname) {
		this.fname = fname;
	}

	@Column(name = "Lname", nullable = false)
	public Serializable getLname() {
		return this.lname;
	}

	public void setLname(Serializable lname) {
		this.lname = lname;
	}

	@Column(name = "Image")
	public Serializable getImage() {
		return this.image;
	}

	public void setImage(Serializable image) {
		this.image = image;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "Status")
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Column(name = "Level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "Salary", precision = 53, scale = 0)
	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
